# -*- coding: utf-8 -*-
"""stockpredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aszfejrqUE79qFA5WLqB7_cU5wxnqOAS
"""

# Description: this program uses an artificial recurrent neural network called LSTM
# to predict the closing stock price of a corporation [apple inc] using the past 60 day stock price

#IMPORTING THE LIBRARIES
import math
import pandas_datareader as web
import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

# GET THE STOCK QUOTE
df = yf.download('AAPL', start='2012-01-01', end='2019-12-17')
# SHOWING THE DATA
df

# GET THE NUMBER OF ROWS AND COLUMNS IN THE DATA SET
df.shape

# VISUALISE THE CLOSING PRICE HISTORY
plt.figure(figsize=(16,8 ))
plt.title('Close Price History')
plt.plot(df['Close'])
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price USD ($)', fontsize=18)
plt.show()

# CREATE A NEW DATA FRAME WITH ONLY CLOSE COLUMN
data = df.filter(['Close'])
# CONVERT DATA FRAME TO A NUMPY ARRAY
dataset = data.values
#GET THE NUMBER OF ROWS TO TRAIN MODEL ON
training_data_len = math.ceil( len(dataset) * 0.8)

training_data_len

# SCALE DATA
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(dataset)

scaled_data

# CREATE THE TRAINING DATA SET
#CREATE THE SCALED TRAINING DATA SET
train_data = scaled_data[0:training_data_len , :]
#SPLIT DATA INTO X_TRAIN AND Y_TRAIN DATA SETS
x_train = []
y_train = []

for i in range(60, len(train_data)):
  x_train.append(train_data[i-60:i, 0])
  y_train.append(train_data[i, 0])
  if i <= 61:
    print(x_train)
    print(y_train)
    print()

# CONVERT X_TRAIN AND Y_TRAIN TO NUMPY ARRAYS
x_train, y_train = np.array(x_train), np.array(y_train)

#RESHAPE THE DATA -> need 3 dimensional data not 2
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_train.shape

# BUILD THE LSTM MODEL
model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape= (x_train.shape[1], 1)))
model.add(LSTM(50, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))

#COMPILING MODEL
model.compile(optimizer= 'adam', loss='mean_squared_error')

#TRAIN MODEL
model.fit(x_train, y_train, batch_size=1, epochs=1)

#CREATE TESTING DATA SET
# CREATE A NEW ARRAY CONTAINING SCCALED VALUES FROM INDEX 1542 TO 2002
test_data = scaled_data[training_data_len - 60: , :]
# CREATE THE DATA SETS X_TEST AND Y_TEST
x_test = []
y_test = dataset[training_data_len: , :]
for i in range(60, len(test_data)):
  x_test.append(test_data[i-60:i, 0])

#CONVERT DATA TO A NUMPY ARRAY
x_test = np.array(x_test)

# RESHAPE THE DATA 2d -> 3d
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

#GET MODELS PREDICTED PRICE VALUES
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)

# GET THE ROOT MEAN SQUARED ERROR [RMSE]
rmse = np.sqrt( np.mean( predictions - y_test)**2 )
rmse

##PLOT THE DATA
train = data[:training_data_len]
valid = data[training_data_len:]
valid['Predictions'] = predictions
#VISUALISE DATA
plt.figure(figsize=(16,8))
plt.title("model")
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price USD ($)', fontsize=18)
plt.plot(train['Close'])
plt.plot(valid[['Close', 'Predictions']])
plt.legend(['Train', 'Val', 'Predictions'], loc= 'lower right')
plt.show()

#SHOW THE VALID AND PREDICTED PRICES
valid

#GET THE QUOTE
apple_quote = yf.download('AAPL', start='2012-01-01', end='2019-12-17')
#CREATE NEW DATA FRAME
new_df = apple_quote.filter(['Close'])
#GET THE LAST SIXTY DAY CLOSING PRICE VALUES AND CONVERT THE DATAFRAME TO AN ARRAY
last_60_days = new_df[-60:].values
#SCALE THE DATA TO BE VALUES BETWEEN 0 AND 1
last_60_days_scaled = scaler.transform(last_60_days)
#CREATE EMPTY LIST
X_test = []
#APPEND THE PAST 60 DAYS
X_test.append(last_60_days_scaled)
#CONVERT THE X_TEST DATA SET TO A NUMPY ARRAY
X_test = np.array(X_test)
#RESHAPE DATA
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
#GET PREDICTED SCALE PRICE
pred_price = model.predict(X_test)
#UNDO THE SCALING
pred_price = scaler.inverse_transform(pred_price)
print(pred_price)

#GET THE QUOTE
apple_quote2 = yf.download('AAPL', start='2019-12-18', end='2019-12-19')
print(apple_quote2['Close'])